// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1gfckQUrLzkKTtjbjOlTpbqsITdpNjzY',
    appId: '1:1058957740478:web:e6aa9aa0e663afbf9f91ef',
    messagingSenderId: '1058957740478',
    projectId: 'fir-flutter-codelab-78d8b',
    authDomain: 'fir-flutter-codelab-78d8b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-78d8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0rcdbnKVyyWSUXtu2IMwI-30uNDCpGU',
    appId: '1:1058957740478:android:68bc4918a87b27cd9f91ef',
    messagingSenderId: '1058957740478',
    projectId: 'fir-flutter-codelab-78d8b',
    storageBucket: 'fir-flutter-codelab-78d8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ejy-Uu_nNp0xuBybK8SFSK5iPKoLUDk',
    appId: '1:1058957740478:ios:47244d7b3a3e51019f91ef',
    messagingSenderId: '1058957740478',
    projectId: 'fir-flutter-codelab-78d8b',
    storageBucket: 'fir-flutter-codelab-78d8b.appspot.com',
    iosClientId: '1058957740478-rp4qsb9eh580tipog7dh701b6g2b5s68.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ejy-Uu_nNp0xuBybK8SFSK5iPKoLUDk',
    appId: '1:1058957740478:ios:47244d7b3a3e51019f91ef',
    messagingSenderId: '1058957740478',
    projectId: 'fir-flutter-codelab-78d8b',
    storageBucket: 'fir-flutter-codelab-78d8b.appspot.com',
    iosClientId: '1058957740478-rp4qsb9eh580tipog7dh701b6g2b5s68.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
